# Generated by Django 2.2 on 2019-04-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_char', models.CharField(db_index=True, max_length=50)),
                ('test_int', models.IntegerField(db_index=True)),
            ],
        ),
    ]
